# Config for SimpleWorldManager
#
# Edit only if the server is not running
# else your changes will be overwritten
#
# Almost everything here should be able
# to be changed with an in-game command

force-load:
  - world
# Example:
#  - world1
#  - world2

enable-portal-linking: true

override-spawn: true
global-spawn:
  world: world
  xyz: default
  # Example:
  # xyz:
  #   - -20 # X
  #   - 64  # Y
  #   - 30  # Z
  #   - 0   # Yaw
  #   - 0   # pitch

world-names:
  - world

worlds:
# Example:
  world:
    name: world
    type: NORMAL
    seed: 12345
    portal-nether: world_nether
    portal-end: world_the_end

# Don't change config-version
config-version: 2